name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node.js v18
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.13.5
        run_install: false

    - name: (env) cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

    - name: Install
      run: pnpm install

    - name: Compiles
      run: pnpm run build

    - name: Run Tests
      run: pnpm test

    - name: Check Types
      run: pnpm run types
